/*
Nama: rafli fairuz pramudya
Nim: 2501082012
Tanggal: 02-Juli-2026
Program: Form Pemesanan Makanan dan Minuman
 */
package pratikum02072026;

/**
 *
 * @author rafli
 */
public class MenuMinuman extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuMinuman.class.getName());

    /**
     * Creates new form MenuMinuman
     */
    public MenuMinuman() {
        initComponents();
    }
    private MenuUtama utama;

    public MenuMinuman(MenuUtama utama) {
        this.utama = utama;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblJudul = new javax.swing.JLabel();
        chkKopi = new javax.swing.JCheckBox();
        chkAir = new javax.swing.JCheckBox();
        txtAir = new javax.swing.JTextField();
        txtJus = new javax.swing.JTextField();
        txtKopi = new javax.swing.JTextField();
        cbAir = new javax.swing.JComboBox<>();
        cbJus = new javax.swing.JComboBox<>();
        cbKopi = new javax.swing.JComboBox<>();
        cbAnekaJus = new javax.swing.JComboBox<>();
        txtJmlAir = new javax.swing.JTextField();
        txtJmlJus = new javax.swing.JTextField();
        txtJmlKopi = new javax.swing.JTextField();
        chkJus = new javax.swing.JCheckBox();
        cbAnekaKopi = new javax.swing.JComboBox<>();
        txtTotal = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        btnTotal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblJudul.setFont(new java.awt.Font("Stencil", 1, 14)); // NOI18N
        lblJudul.setForeground(new java.awt.Color(51, 0, 0));
        lblJudul.setText("MENU MINUMAN KAFE TIARA");

        chkKopi.setText("Kopi");
        chkKopi.addActionListener(this::chkKopiActionPerformed);

        chkAir.setText("Mineral");
        chkAir.addActionListener(this::chkAirActionPerformed);

        txtAir.setText("0");

        txtJus.setText("0");

        txtKopi.setText("0");
        txtKopi.addActionListener(this::txtKopiActionPerformed);

        cbAir.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah Pesanan", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbAir.addActionListener(this::cbAirActionPerformed);

        cbJus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah Pesanan", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbJus.addActionListener(this::cbJusActionPerformed);

        cbKopi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah Pesanan", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbKopi.addActionListener(this::cbKopiActionPerformed);

        cbAnekaJus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aneka Jus", "Jus Avocado", "Jus Jeruk", "Jus Mangga", "Jus Naga", "Jus Nanas", "Jus Pisang", "Jus Strowberry", "Mix Jus" }));
        cbAnekaJus.addActionListener(this::cbAnekaJusActionPerformed);

        txtJmlAir.setText("0");

        txtJmlJus.setText("0");

        txtJmlKopi.setText("0");

        chkJus.setText("Jus");
        chkJus.addActionListener(this::chkJusActionPerformed);

        cbAnekaKopi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aneka Kopi", "Americano", "Butterscoat", "Coppucinno", "Kopi Milk", "Latte", "Sea Salt", " ", " " }));
        cbAnekaKopi.addActionListener(this::cbAnekaKopiActionPerformed);

        txtTotal.setText("0");

        btnReset.setText("Reset");
        btnReset.addActionListener(this::btnResetActionPerformed);

        btnKembali.setText("Back");
        btnKembali.addActionListener(this::btnKembaliActionPerformed);

        btnTotal.setText("Total");
        btnTotal.addActionListener(this::btnTotalActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkKopi)
                            .addComponent(chkAir, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkJus, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtJus, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(txtAir)
                            .addComponent(txtKopi))
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTotal)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnReset))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 8, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbAnekaKopi, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbAnekaJus, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbJus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbKopi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbAir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblJudul)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnKembali)
                        .addGap(120, 120, 120))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtJmlKopi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(txtJmlAir, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtJmlJus, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(185, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblJudul)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkAir)
                    .addComponent(cbAir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJmlAir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbAnekaJus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJmlJus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkJus)
                    .addComponent(cbJus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkKopi)
                    .addComponent(txtKopi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbKopi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJmlKopi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbAnekaKopi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTotal))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKembali)
                    .addComponent(btnReset))
                .addGap(50, 50, 50))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtKopiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKopiActionPerformed
    
    }//GEN-LAST:event_txtKopiActionPerformed

    private void chkAirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAirActionPerformed
        txtAir.setText("15000");
    }//GEN-LAST:event_chkAirActionPerformed

    private void chkJusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkJusActionPerformed
        txtJus.setText("25000");
    }//GEN-LAST:event_chkJusActionPerformed

    private void chkKopiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkKopiActionPerformed
       txtKopi.setText("65000");
    }//GEN-LAST:event_chkKopiActionPerformed

    private void cbAnekaJusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAnekaJusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAnekaJusActionPerformed

    private void cbAnekaKopiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAnekaKopiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAnekaKopiActionPerformed

    private void cbAirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAirActionPerformed
        int jumlah = (int)cbAir.getSelectedIndex();
        double harga = Double.parseDouble(txtAir.getText());
        double total = harga * jumlah;
        txtJmlAir.setText(Double.toString(total));
        
    }//GEN-LAST:event_cbAirActionPerformed

    private void cbJusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJusActionPerformed
      int jumlah = (int)cbJus.getSelectedIndex();
      double harga = Double.parseDouble(txtJus.getText());
      double total = harga * jumlah;
      txtJmlJus.setText(Double.toString(total));
    }//GEN-LAST:event_cbJusActionPerformed

    private void cbKopiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKopiActionPerformed
        int jumlah = (int)cbKopi.getSelectedIndex();
        double harga = Double.parseDouble(txtKopi.getText());
        double total = harga * jumlah;
        txtJmlKopi.setText(Double.toString(total));
    }//GEN-LAST:event_cbKopiActionPerformed

    private void btnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalActionPerformed
        double air = Double.parseDouble(txtJmlAir.getText());
        double jus = Double.parseDouble(txtJmlJus.getText());
        double kopi = Double.parseDouble(txtJmlKopi.getText());
        double total = air + jus + kopi;
        txtTotal.setText(Double.toString(total));
    }//GEN-LAST:event_btnTotalActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtAir.setText("");
        txtJus.setText("");
        txtKopi.setText("");
        txtTotal.setText("");
        txtJmlAir.setText("");
        txtJmlJus.setText("");
        txtJmlKopi.setText("");
        
      
        
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
       String total = txtTotal.getText(); 
       utama.setTotalMinuman(total);
       this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuMinuman().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTotal;
    private javax.swing.JComboBox<String> cbAir;
    private javax.swing.JComboBox<String> cbAnekaJus;
    private javax.swing.JComboBox<String> cbAnekaKopi;
    private javax.swing.JComboBox<String> cbJus;
    private javax.swing.JComboBox<String> cbKopi;
    private javax.swing.JCheckBox chkAir;
    private javax.swing.JCheckBox chkJus;
    private javax.swing.JCheckBox chkKopi;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JTextField txtAir;
    private javax.swing.JTextField txtJmlAir;
    private javax.swing.JTextField txtJmlJus;
    private javax.swing.JTextField txtJmlKopi;
    private javax.swing.JTextField txtJus;
    private javax.swing.JTextField txtKopi;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
