/*
Nama: rafli fairuz pramudya
Nim: 2501082012
Tanggal: 02-Juli-2026
Program: Form Pemesanan Makanan dan Minuman
 */
package pratikum02072026;

import javax.swing.JOptionPane;

/**
 *
 * @author rafli
 */
public class MenuMakanan extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuMakanan.class.getName());

    /**
     * Creates new form MenuMakanan
     */
    public MenuMakanan() {
        initComponents();
    }
    
    private MenuUtama utama;

    public MenuMakanan(MenuUtama utama) {
        this.utama = utama;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblJudul = new javax.swing.JLabel();
        chkNasgor = new javax.swing.JCheckBox();
        chkSate = new javax.swing.JCheckBox();
        chkSoto = new javax.swing.JCheckBox();
        txtNasgor = new javax.swing.JTextField();
        txtSate = new javax.swing.JTextField();
        txtSoto = new javax.swing.JTextField();
        cbNasgor = new javax.swing.JComboBox<>();
        cbSate = new javax.swing.JComboBox<>();
        cbSoto = new javax.swing.JComboBox<>();
        txtTotalNasgor = new javax.swing.JTextField();
        txtTotalSate = new javax.swing.JTextField();
        txtTotalSoto = new javax.swing.JTextField();
        btnTotal = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        txtTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblJudul.setFont(new java.awt.Font("Stencil", 1, 14)); // NOI18N
        lblJudul.setForeground(new java.awt.Color(102, 0, 0));
        lblJudul.setText("MENU MAKANAN KAFE TIARA");

        chkNasgor.setText("Nasi goreng");
        chkNasgor.addActionListener(this::chkNasgorActionPerformed);

        chkSate.setText("Sate");
        chkSate.addActionListener(this::chkSateActionPerformed);

        chkSoto.setText("Soto");
        chkSoto.addActionListener(this::chkSotoActionPerformed);

        txtNasgor.setText("0");

        txtSate.setText("0");

        txtSoto.setText("0");

        cbNasgor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah Pesanan", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbNasgor.addActionListener(this::cbNasgorActionPerformed);

        cbSate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah Pesanan", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbSate.addActionListener(this::cbSateActionPerformed);

        cbSoto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah Pesanan", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbSoto.addActionListener(this::cbSotoActionPerformed);

        txtTotalNasgor.setText("0");

        txtTotalSate.setText("0");

        txtTotalSoto.setText("0");

        btnTotal.setText("Total");
        btnTotal.addActionListener(this::btnTotalActionPerformed);

        btnKembali.setText("Back");
        btnKembali.addActionListener(this::btnKembaliActionPerformed);

        btnReset.setText("Reset");
        btnReset.addActionListener(this::btnResetActionPerformed);

        txtTotal.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(chkSoto, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtSoto))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(chkNasgor)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtNasgor, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(chkSate, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtSate, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(98, 98, 98)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbSate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbSoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtTotalSoto, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtTotalSate, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(cbNasgor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtTotalNasgor, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnTotal)
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnReset)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnKembali)
                                        .addGap(66, 66, 66))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(lblJudul)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblJudul)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkNasgor)
                    .addComponent(cbNasgor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNasgor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalNasgor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(chkSate))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbSate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTotalSate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTotalSoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(chkSoto))
                    .addComponent(cbSoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTotal)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReset)
                    .addComponent(btnKembali))
                .addGap(35, 35, 35))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void chkNasgorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkNasgorActionPerformed
        txtNasgor.setText("100000");
    }//GEN-LAST:event_chkNasgorActionPerformed

    private void chkSateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSateActionPerformed
        txtSate.setText("150000");
    }//GEN-LAST:event_chkSateActionPerformed

    private void chkSotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSotoActionPerformed
        txtSoto.setText("200000");
    }//GEN-LAST:event_chkSotoActionPerformed

    private void cbNasgorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNasgorActionPerformed
        int jumlah = (int)cbNasgor.getSelectedIndex();
        double harga = Double.parseDouble(txtNasgor.getText());
        double total = jumlah * harga;
        txtTotalNasgor.setText(Double.toString(total));
    }//GEN-LAST:event_cbNasgorActionPerformed

    private void cbSateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSateActionPerformed
        int jumlah = (int)cbSate.getSelectedIndex();
        double harga = Double.parseDouble(txtSate.getText());
        double total = jumlah * harga;
        txtTotalSate.setText(Double.toString(total));
    }//GEN-LAST:event_cbSateActionPerformed

    private void cbSotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSotoActionPerformed
        int jumlah = (int)cbSoto.getSelectedIndex();
        double harga = Double.parseDouble(txtSoto.getText());
        double total = jumlah * harga;
        txtTotalSoto.setText(Double.toString(total));
    }//GEN-LAST:event_cbSotoActionPerformed

    private void btnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalActionPerformed
        double nasgor = Double.parseDouble(txtTotalNasgor.getText());
        double sate = Double.parseDouble(txtTotalSate.getText());
        double soto = Double.parseDouble(txtTotalSoto.getText());
        double total = nasgor + sate + soto;
        txtTotal.setText(Double.toString(total));
    }//GEN-LAST:event_btnTotalActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
       txtNasgor.setText("");
       txtSate.setText("");
       txtSoto.setText("");
       txtTotal.setText("");
       txtTotalNasgor.setText("");
       txtTotalSate.setText("");
       txtTotalSoto.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        
       String total = txtTotal.getText(); 
       utama.setTotalMakanan(total);
       this.dispose();
       
    }//GEN-LAST:event_btnKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuMakanan().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTotal;
    private javax.swing.JComboBox<String> cbNasgor;
    private javax.swing.JComboBox<String> cbSate;
    private javax.swing.JComboBox<String> cbSoto;
    private javax.swing.JCheckBox chkNasgor;
    private javax.swing.JCheckBox chkSate;
    private javax.swing.JCheckBox chkSoto;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JTextField txtNasgor;
    private javax.swing.JTextField txtSate;
    private javax.swing.JTextField txtSoto;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTotalNasgor;
    private javax.swing.JTextField txtTotalSate;
    private javax.swing.JTextField txtTotalSoto;
    // End of variables declaration//GEN-END:variables
}
